# site title
title: FIX

# user name or organization name
user: yulb2020

# issue repository
repository: yulb2020.github.io

# multi-author
authors: yulb

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 5#f33b6dbbafac819fdf30039c572d3a57836ac48

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
